
spring:
  # TODO 配置数据源相关信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qq_chat
    username: root
    password: 123456

server:
  port: 8080
  address: localhost


logging:
  level:
    root: info

